Additional stock MK3S hardware support
Rat-OS/RatOS-configurator pull request #58
Opened 2024-12-28 22:18 UTC by kronflux

Added LCD backlight control and Einsy board temperature sensor

2025-01-02 22:03 UTC, miklschmidt requested changes

2025-01-02 22:03 UTC, miklschmidt commented on configuration/boards/prusa-einsy/config.cfg
> +[temperature_sensor einsy]
This won't work in 2.1, the configurator only uses this file to read the board alias map. You can put it in the template, commented out, like you did with the display backlight pin. It's ugly, but there's no other way to do non-standard things currently.

2025-01-02 22:03 UTC, miklschmidt commented on configuration/boards/prusa-einsy/config.cfg
> +  display_backlight_pin=PE3,
This is not a standard pin alias (neither are the other display_* aliases, they aren't used, they're only there for backwards compatibility with 2.0 configs) and will be ignored by the configurator. Remove it.

2025-01-02 22:03 UTC, miklschmidt commented on configuration/printers/prusa-mk3s/display.cfg
> +[output_pin LCD_backlight_pin]
This section should be removed. RatOS currently has no concept of lcd displays. There's a feature in development to allow for "accessories" to support arbitrary things like this, until then it will have to be a commented out section in the printer.cfg template.

2025-01-02 22:03 UTC, miklschmidt commented on configuration/printers/prusa-mk3s/display.cfg
>  [output_pin BEEPER_pin]
Similar for this actually, this should also be removed (or moved to the printer template)

2025-01-02 22:03 UTC, miklschmidt commented on src/data/steppers.ts
> +		presets: [
Where do these values come from?

2025-01-16 03:52 UTC, kronflux commented on src/data/steppers.ts
> +		presets: [
From the datasheet for the motor itself, and referencing other klipper configurations for the MK3S they appear to be referencing the datasheet as well

2025-01-16 04:03 UTC, kronflux commented
my machine actually kicked the bucket, something up with my hotend so I won't be able to make adjustments or test this further, but hopefully some of it is helpful
Feel free to merge or discard whatever you wish :)

2026-08-19 22:52 UTC, closed without merging